#Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "543968496399-tf-remote-state1"
    dynamodb_table = "543968496399-tf-remote-state1-lock"
    encrypt        = true
    key            = "accounts/network-services/setup-terraform-backend/terraform.tfstate"
    region         = "us-east-1"
  }
}
