# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "157489942873-tf-remote-state"
    dynamodb_table = "157489942873-tf-remote-state-lock"
    encrypt        = true
    key            = "accounts/production-services/setup-rancher/terraform.tfstate"
    region         = "us-east-1"
  }
}
