apiVersion: apps/v1

kind: Deployment

metadata:

  name: inflate-karpenter

spec:

  replicas: 1

  selector:

    matchLabels:

      app: inflate

  template:

    metadata:

      labels:

        app: inflate

    spec:

      containers:

      - name: inflate

        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7

        resources:

          requests:

            cpu: "4"        # maior que os nodes atuais

            memory: "6Gi"