# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "499897076270-tf-remote-state"
    dynamodb_table = "499897076270-tf-remote-state-lock"
    encrypt        = true
    key            = "accounts/network-services/setup-account/terraform.tfstate"
    region         = "us-east-1"
  }
}
