# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "582577266226-tf-remote-state"
    dynamodb_table = "582577266226-tf-remote-state-lock"
    encrypt        = true
    key            = "accounts/production-services/setup-dns/terraform.tfstate"
    region         = "us-east-1"
  }
}
